INPUT_FILENAME ="/home/amarante/Bureau/Projets/fac/Tatia/projet-tatia/data/Corpus_FleurDuMal.txt"
CORPUS_FILENAME_LOWER = "/home/amarante/Bureau/Projets/fac/Tatia/projet-tatia/data/Corpus_RAPFR_lower_cleaner.txt"
OUTPUT_FILENAME_NGRAM = "/home/amarante/Bureau/Projets/fac/Tatia/projet-tatia/out/prod-Ngram.txt"
OUTPUT_FILENAME_MARKOV = "/home/amarante/Bureau/Projets/fac/Tatia/projet-tatia/out/prod-Markov.txt"
IMPORTED_TABLE_FILENAME_NGRAM = "/home/amarante/Bureau/Projets/fac/Tatia/projet-tatia/src/ngrammesAndQlearning/table_dump.json"